"""Public interface-building API for graphite/polymer/electrolyte workflows.

The interface package exposes the higher-level route planners, slab builders,
bulk calibration helpers, and sandwich convenience constructors. Importing from
this module keeps user scripts short while implementation details remain split
across focused submodules.
"""

from __future__ import annotations

from .builder import (
    AreaMismatchPolicy,
    BulkSource,
    BuiltInterface,
    InterfaceBuilder,
    InterfaceRouteSpec,
    PreparedSlab,
    SlabBuildSpec,
    build_interface,
    build_interface_from_workdirs,
)
from .bulk_resize import (
    BulkEquilibriumProfile,
    BulkRescalePlan,
    DirectElectrolytePlan,
    ElectrolyteAlignmentPlan,
    FixedXYDirectPackPlan,
    build_bulk_equilibrium_profile,
    fixed_xy_semiisotropic_npt_overrides,
    plan_fixed_xy_direct_pack_box,
    plan_direct_electrolyte_counts,
    plan_rescaled_bulk_counts,
    plan_resized_electrolyte_counts,
    read_equilibrated_box_nm,
    recommend_electrolyte_alignment,
)
from .charge_audit import format_cell_charge_audit, format_charge_meta_audit, summarize_cell_charge, summarize_charge_meta
from .postprocess import build_interface_group_catalog, export_interface_group_catalog, read_ndx_groups
from .prep import (
    BulkEq21Outcome,
    DirectPolymerMatchedInterfacePreparation,
    FixedXYElectrolytePreparation,
    PolymerAnchoredInterfacePreparation,
    PolymerDiffusionInterfaceRecipe,
    ProbePolymerMatchedInterfacePreparation,
    ProbeElectrolytePreparation,
    ResizedPolymerMatchedInterfacePreparation,
    ResizedElectrolytePreparation,
    equilibrate_bulk_with_eq21,
    make_orthorhombic_pack_cell,
    plan_direct_polymer_matched_interface_preparation,
    plan_fixed_xy_direct_electrolyte_preparation,
    plan_polymer_anchored_interface_preparation,
    plan_probe_polymer_matched_interface_preparation,
    plan_probe_electrolyte_preparation,
    plan_resized_polymer_matched_interface_from_probe,
    plan_resized_electrolyte_preparation_from_probe,
    recommend_polymer_diffusion_interface_recipe,
)
from .protocol import InterfaceDynamics, InterfaceProtocol, InterfaceStageSpec
from .sandwich import (
    BulkCalibrationResult,
    ElectrolyteSlabSpec,
    GraphitePreparationResult,
    GraphitePolymerElectrolyteSandwichResult,
    GraphiteSubstrateSpec,
    InterfaceBuildPolicy,
    InterfaceTransportResult,
    InterphaseBuildResult,
    MoleculeSpec,
    PolymerSlabSpec,
    SandwichPhaseReport,
    SandwichRelaxationSpec,
    StackReleaseResult,
    analyze_interface_transport,
    build_cmc_electrolyte_interphase,
    build_cmcna_graphite_electrolyte_stack,
    build_graphite_cmc_interphase,
    build_graphite_cmcna_glucose6_periodic_case,
    build_graphite_cmcna_electrolyte_sandwich,
    build_graphite_polymer_interphase,
    build_graphite_peo_electrolyte_sandwich,
    build_polymer_electrolyte_interphase,
    build_graphite_polymer_electrolyte_sandwich,
    calibrate_electrolyte_bulk_phase,
    calibrate_polymer_bulk_phase,
    default_carbonate_lipf6_electrolyte_spec,
    default_cmcna_polymer_spec,
    default_peo_electrolyte_spec,
    default_peo_polymer_spec,
    prepare_graphite_substrate,
    print_interface_result_summary,
    release_graphite_cmc_electrolyte_stack,
    release_graphite_polymer_electrolyte_stack,
)
from .sandwich_examples import (
    build_graphite_cmcna_example_case,
    build_graphite_peo_example_case,
    format_sandwich_result_summary,
    print_sandwich_result_summary,
)

__all__ = [
    "AreaMismatchPolicy",
    "BulkEquilibriumProfile",
    "BulkRescalePlan",
    "BulkEq21Outcome",
    "BulkCalibrationResult",
    "DirectPolymerMatchedInterfacePreparation",
    "DirectElectrolytePlan",
    "ElectrolyteAlignmentPlan",
    "FixedXYElectrolytePreparation",
    "PolymerAnchoredInterfacePreparation",
    "PolymerDiffusionInterfaceRecipe",
    "ProbePolymerMatchedInterfacePreparation",
    "ProbeElectrolytePreparation",
    "ResizedPolymerMatchedInterfacePreparation",
    "ResizedElectrolytePreparation",
    "FixedXYDirectPackPlan",
    "BulkSource",
    "BuiltInterface",
    "InterfaceBuilder",
    "InterfaceRouteSpec",
    "PreparedSlab",
    "SlabBuildSpec",
    "build_bulk_equilibrium_profile",
    "build_interface",
    "build_interface_from_workdirs",
    "build_interface_group_catalog",
    "equilibrate_bulk_with_eq21",
    "plan_direct_polymer_matched_interface_preparation",
    "plan_direct_electrolyte_counts",
    "plan_fixed_xy_direct_pack_box",
    "plan_fixed_xy_direct_electrolyte_preparation",
    "plan_polymer_anchored_interface_preparation",
    "plan_probe_polymer_matched_interface_preparation",
    "plan_probe_electrolyte_preparation",
    "plan_resized_polymer_matched_interface_from_probe",
    "plan_resized_electrolyte_preparation_from_probe",
    "recommend_polymer_diffusion_interface_recipe",
    "format_cell_charge_audit",
    "format_charge_meta_audit",
    "fixed_xy_semiisotropic_npt_overrides",
    "InterfaceDynamics",
    "export_interface_group_catalog",
    "InterfaceProtocol",
    "InterfaceStageSpec",
    "GraphiteSubstrateSpec",
    "GraphitePreparationResult",
    "InterfaceBuildPolicy",
    "PolymerSlabSpec",
    "ElectrolyteSlabSpec",
    "InterphaseBuildResult",
    "StackReleaseResult",
    "InterfaceTransportResult",
    "MoleculeSpec",
    "SandwichPhaseReport",
    "SandwichRelaxationSpec",
    "prepare_graphite_substrate",
    "calibrate_polymer_bulk_phase",
    "calibrate_electrolyte_bulk_phase",
    "build_graphite_polymer_interphase",
    "build_graphite_cmc_interphase",
    "build_polymer_electrolyte_interphase",
    "build_cmc_electrolyte_interphase",
    "build_cmcna_graphite_electrolyte_stack",
    "release_graphite_polymer_electrolyte_stack",
    "release_graphite_cmc_electrolyte_stack",
    "analyze_interface_transport",
    "GraphitePolymerElectrolyteSandwichResult",
    "build_graphite_cmcna_glucose6_periodic_case",
    "build_graphite_cmcna_example_case",
    "build_graphite_cmcna_electrolyte_sandwich",
    "build_graphite_polymer_electrolyte_sandwich",
    "build_graphite_peo_example_case",
    "build_graphite_peo_electrolyte_sandwich",
    "default_carbonate_lipf6_electrolyte_spec",
    "default_cmcna_polymer_spec",
    "default_peo_polymer_spec",
    "default_peo_electrolyte_spec",
    "print_interface_result_summary",
    "format_sandwich_result_summary",
    "make_orthorhombic_pack_cell",
    "plan_rescaled_bulk_counts",
    "plan_resized_electrolyte_counts",
    "read_equilibrated_box_nm",
    "read_ndx_groups",
    "recommend_electrolyte_alignment",
    "summarize_cell_charge",
    "summarize_charge_meta",
    "print_sandwich_result_summary",
]
