"""Public interface-building API for graphite/polymer/electrolyte workflows.

The recommended high-level route is the generic ``layer_stack`` engine: scripts
describe ordered layers, and YadonPy plans, packs, stacks, exports, samples, and
analyzes that system.  Older sandwich-specific public APIs were removed so new
workflows do not silently use stale geometry assumptions.
"""

from __future__ import annotations

from .builder import (
    AreaMismatchPolicy,
    BulkSource,
    BuiltInterface,
    InterfaceBuilder,
    InterfaceRouteSpec,
    PreparedSlab,
    SlabBuildSpec,
    build_interface,
    build_interface_from_workdirs,
)
from .bulk_resize import (
    BulkEquilibriumProfile,
    BulkRescalePlan,
    DirectElectrolytePlan,
    ElectrolyteAlignmentPlan,
    FixedXYDirectPackPlan,
    build_bulk_equilibrium_profile,
    fixed_xy_semiisotropic_npt_overrides,
    plan_fixed_xy_direct_pack_box,
    plan_direct_electrolyte_counts,
    plan_rescaled_bulk_counts,
    plan_resized_electrolyte_counts,
    read_equilibrated_box_nm,
    recommend_electrolyte_alignment,
)
from .charge_audit import format_cell_charge_audit, format_charge_meta_audit, summarize_cell_charge, summarize_charge_meta
from .layer_stack import (
    ElectrodeChargeSpec,
    GraphiteLayerSpec,
    LayerStackNvtResult,
    LayerStackRelaxationSpec,
    LayerStackResult,
    LayerStackSpec,
    MolecularLayerSpec,
    VacuumLayerSpec,
    analyze_layer_stack_interface,
    build_layer_stack,
    run_layer_stack_nvt,
)
from .postprocess import build_interface_group_catalog, export_interface_group_catalog, read_ndx_groups
from .prep import (
    BulkEq21Outcome,
    DirectPolymerMatchedInterfacePreparation,
    FixedXYElectrolytePreparation,
    PolymerAnchoredInterfacePreparation,
    PolymerDiffusionInterfaceRecipe,
    ProbePolymerMatchedInterfacePreparation,
    ProbeElectrolytePreparation,
    ResizedPolymerMatchedInterfacePreparation,
    ResizedElectrolytePreparation,
    equilibrate_bulk_with_eq21,
    make_orthorhombic_pack_cell,
    plan_direct_polymer_matched_interface_preparation,
    plan_fixed_xy_direct_electrolyte_preparation,
    plan_polymer_anchored_interface_preparation,
    plan_probe_polymer_matched_interface_preparation,
    plan_probe_electrolyte_preparation,
    plan_resized_polymer_matched_interface_from_probe,
    plan_resized_electrolyte_preparation_from_probe,
    recommend_polymer_diffusion_interface_recipe,
)
from .protocol import InterfaceDynamics, InterfaceProtocol, InterfaceStageSpec

__all__ = [
    "AreaMismatchPolicy",
    "BulkEquilibriumProfile",
    "BulkRescalePlan",
    "BulkEq21Outcome",
    "DirectPolymerMatchedInterfacePreparation",
    "DirectElectrolytePlan",
    "ElectrolyteAlignmentPlan",
    "FixedXYElectrolytePreparation",
    "PolymerAnchoredInterfacePreparation",
    "PolymerDiffusionInterfaceRecipe",
    "ProbePolymerMatchedInterfacePreparation",
    "ProbeElectrolytePreparation",
    "ResizedPolymerMatchedInterfacePreparation",
    "ResizedElectrolytePreparation",
    "FixedXYDirectPackPlan",
    "ElectrodeChargeSpec",
    "GraphiteLayerSpec",
    "LayerStackNvtResult",
    "LayerStackRelaxationSpec",
    "LayerStackResult",
    "LayerStackSpec",
    "MolecularLayerSpec",
    "VacuumLayerSpec",
    "BulkSource",
    "BuiltInterface",
    "InterfaceBuilder",
    "InterfaceRouteSpec",
    "PreparedSlab",
    "SlabBuildSpec",
    "build_bulk_equilibrium_profile",
    "build_interface",
    "build_interface_from_workdirs",
    "build_layer_stack",
    "analyze_layer_stack_interface",
    "run_layer_stack_nvt",
    "build_interface_group_catalog",
    "equilibrate_bulk_with_eq21",
    "plan_direct_polymer_matched_interface_preparation",
    "plan_direct_electrolyte_counts",
    "plan_fixed_xy_direct_pack_box",
    "plan_fixed_xy_direct_electrolyte_preparation",
    "plan_polymer_anchored_interface_preparation",
    "plan_probe_polymer_matched_interface_preparation",
    "plan_probe_electrolyte_preparation",
    "plan_resized_polymer_matched_interface_from_probe",
    "plan_resized_electrolyte_preparation_from_probe",
    "recommend_polymer_diffusion_interface_recipe",
    "format_cell_charge_audit",
    "format_charge_meta_audit",
    "fixed_xy_semiisotropic_npt_overrides",
    "InterfaceDynamics",
    "export_interface_group_catalog",
    "InterfaceProtocol",
    "InterfaceStageSpec",
    "make_orthorhombic_pack_cell",
    "plan_rescaled_bulk_counts",
    "plan_resized_electrolyte_counts",
    "read_equilibrated_box_nm",
    "read_ndx_groups",
    "recommend_electrolyte_alignment",
    "summarize_cell_charge",
    "summarize_charge_meta",
]
